Run npm test
npm error Missing script: "test"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: 
/home/runner/.npm/_logs/2026-01-09T12_49_51_797Z-debug-0.log
Error: Process completed with exit code 1.

